theme = "onelight"

[editor]
line-number = "relative"
true-color = true
idle-timeout = 1
auto-save = true
color-modes = true
auto-pairs = true
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "version-control",
  "file-modification-indicator",
]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = true
git-ignore = true

[keys.select]
z = { r = [
  'commit_undo_checkpoint',
  'normal_mode',
  ':update',
], z = [
  'commit_undo_checkpoint',
  'normal_mode',
] }

[keys.normal]
z = { r = [
  'commit_undo_checkpoint',
  'normal_mode',
  ':update',
], z = [
  'commit_undo_checkpoint',
  'normal_mode',
] }

[keys.insert]
z = { r = [
  'commit_undo_checkpoint',
  'normal_mode',
  ':update',
], z = [
  'commit_undo_checkpoint',
  'normal_mode',
] }

up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
